### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by pkrogel-kws** [c0bra/rete-svelte-render-plugin#2]
Is there any chance you could provide a basic demo/starter?  I've been trying to get this running all day.

**Comment by c0bra** [comment]
Yea I can try.

Can you share what issue you're having?

**Comment by pkrogel-kws** [comment]
Thanks for getting back to me!  For starters, I tried installing your package and running as is, but I wasn't getting anything inside the Rete component wrappers (empty divs).  To try and figure out what was going on, I pulled all your code into the project itself, and started adding some trusty console debug statements.  What I found was that in index.js (install function), this line was returning false:

`if (!component.render || component.render !== "svelte") return;`

Looking at the official React plugin for reference, I changed it to:
`if (component.render && component.render !== "svelte") return;`
This resolves the initial empty div issue (I now get components), but when I try to connect sockets or change the input values, I get errors like `TypeError: component is undefined`. 

More than likely, I am just failing to use the plugin correctly.  I am essentially just trying to port the official demo (NumComponent and AddComponent) over to Svelte using your plugin so there is a starter to work off of.

**Comment by pkrogel-kws** [comment]
Friendly ping :)

**Comment by pkrogel-kws** [comment]
I got it working.

**Comment by c0bra** [comment]
@pkrogel-kws glad you were able to fix it! Sorry for not lending any help.

**Comment by gevrum** [comment]
@pkrogel-kws  > I got it working.

How did you manage to launch the application with this plugin?
